server:
  port: 8081

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: gateway-api
  cloud:
    gateway:
      routes:
        - id: google
          uri: https://google.com
          predicates:
            - Path=/search/**